// react-frontend/src/components/Board.tsx
import React, { useState } from 'react';
import './Board.css'; // Import the CSS file
// import Section from './Section';
import Switch from '@mui/material/Switch';
import { host_api, sections } from '../utils/Constants';
import Typography from '@mui/material/Typography';
import { useNavigate } from 'react-router-dom';
import { 
  Dialog, DialogTitle, DialogContent, Button, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper 
} from '@mui/material';
import { useAuth } from '../AuthContext';

interface ScoreTally {
  username:string;
  firstname:string;
  lastname:string;
  total_points:number;
}
interface BoardProps {
  // handleIndexSelect:(index:number) => void;
  // handleIsCumulative:(isCumulative:boolean) => void;
  handleGameParams: (index:number,isCumulative:boolean) => void;
  playerUsername:string;


}
const Board: React.FC<BoardProps> = ({handleGameParams,playerUsername}) => {
  const [isCumulative, setIsCumulative] = useState<boolean>(false);
  const [selectedSectionIndex,setSelectedSectionIndex] = useState<number>(-1);
  const [scoreboardData,setScoreboardData] = useState<ScoreTally[]>([]);
  const navigate = useNavigate();

  // const currentUser = playerUsername; // Current user's name

  
    const [open, setOpen] = useState(false);
    const { logout } = useAuth();
   

   const handleSignOut = () => {
    logout(); // Clear the authentication state
    navigate('/login'); // Redirect to login page
  };
    const handleOpenDialog = () => {
      
      getScoreboardData();
      setOpen(true);
    };

    const handleCloseDialog = () => {
      setOpen(false);
    };

  const handleSectionClick = (index: number) => {
    setSelectedSectionIndex(index)
  };

  const handleContinueClick = () => {
    handleGameParams(selectedSectionIndex,isCumulative)
    navigate('/game'); // Navigate to the Game route
  };

  const handleToggle = (event: React.ChangeEvent<HTMLInputElement>) => {
    setIsCumulative(event.target.checked)
  };

  const getScoreboardData  = async () => {
    
      try {
        const response = await fetch(`${host_api}/scoreboard`); // Replace with your API endpoint
        const data = await response.json();
        const scoreboardData : ScoreTally[] = data.map((el:ScoreTally) => ({username:el.username,firstname:el.firstname,lastname:el.lastname,total_points:el.total_points}))
        setScoreboardData(scoreboardData)
      } catch (error) {
        console.error('Error fetching users:', error);
      }
    

  }

  return (
    <div className="board">
      {sections.map((section, index) => (
         <div className={section.css_id}
         style={selectedSectionIndex === index || (isCumulative && index < selectedSectionIndex) ? {border: '3px solid black' } : {border:'none'}}
         onClick={() => handleSectionClick(index)} 
         key={index}
         
        //  onClick={() => isActive ? handleLetterClick(letter['unicode'], index) : null}
       >
         <img src={section['sectionPngPath']} style={{height:'200px', width:'650px'}} alt="Description of the image" />
       </div>
  
      ))}
       <Button 
               variant="contained" 
               color="success" 
               onClick={handleContinueClick} 
               disabled={selectedSectionIndex < 0}
               sx={{ position:"fixed", justifyContent:"center", alignContent:"center" , top:"50%"}}>
        Continue
      </Button>
        <div style= {{ position:"fixed", bottom:"20px", left:"10px", marginLeft:"50px" }} >
        <Typography variant="body1">Cumulative ?</Typography>
      <Switch
        // checked={isEnabled}
        // sx={{ position:"fixed", justifyContent:"center", alignContent:"center" , top:"40%"}}
        onChange={handleToggle}
        color="primary"
      />
        </div>
         
       <Button 
          variant="contained" 
          color="secondary" 
          onClick={handleSignOut}
          sx={{ position:"fixed", bottom:"10px", right:"10px" }}
        >
          Sign Out
        </Button>
        <Button variant="contained" 
                color="primary" 
                onClick={handleOpenDialog}
                sx={{ position:"fixed", bottom:"10px", right:"100px", marginRight:"50px" }}>
       Scoreboard
      </Button>
       {/* Dialog containing the scoreboard */}
       <Dialog open={open} onClose={handleCloseDialog} maxWidth="sm" fullWidth>
        <DialogTitle>Scoreboard</DialogTitle>
        <DialogContent>
          <TableContainer component={Paper}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Name</TableCell>
                  <TableCell align="right">Points</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {scoreboardData.map((score, index) => (
                  <TableRow key={index}>
                    <TableCell style={score.username === playerUsername ? { fontWeight: 'bold' } : {}}>
                    {score.lastname}, {score.firstname}
                    </TableCell>
                    <TableCell align="right" style={score.username === playerUsername ? { fontWeight: 'bold' } : {}}>
                      {score.total_points}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </DialogContent>
      </Dialog>
    </div>
    
  );
};

export default Board;

// angular-frontend/src/app/components/board/board.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatTableModule } from '@angular/material/table';
import { AuthService } from '../../core/services/auth.service';
import { ApiService } from '../../core/services/api.service';
import { sections } from '../../utils/constants';
import { ScoreTally } from '../../models/user.model';
import { ScoreboardDialogComponent } from './scoreboard-dialog.component';

@Component({
  selector: 'app-board',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatButtonModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatTableModule
  ],
  templateUrl: './board.component.html',
  styleUrl: './board.component.css'
})
export class BoardComponent implements OnInit {
  sections = sections;
  isCumulative = false;
  selectedSectionIndex = -1;
  playerUsername = '';

  constructor(
    private authService: AuthService,
    private apiService: ApiService,
    private router: Router,
    private dialog: MatDialog
  ) {}

  ngOnInit(): void {
    this.authService.username$.subscribe(username => {
      this.playerUsername = username;
    });
  }

  handleSectionClick(index: number): void {
    this.selectedSectionIndex = index;
  }

  handleContinue(): void {
    this.router.navigate(['/game'], {
      state: {
        selectedSectionsIndex: this.selectedSectionIndex,
        isCumulative: this.isCumulative,
        playerUsername: this.playerUsername
      }
    });
  }

  handleSignOut(): void {
    this.authService.logout();
    this.router.navigate(['/login']);
  }

  openScoreboard(): void {
    this.apiService.getScoreboard().subscribe({
      next: (data) => {
        const sortedData = data.sort((a, b) => b.total_points - a.total_points);
        this.dialog.open(ScoreboardDialogComponent, {
          width: '600px',
          data: { scoreboardData: sortedData, currentUsername: this.playerUsername }
        });
      },
      error: (error) => {
        console.error('Error fetching scoreboard:', error);
      }
    });
  }

  isSectionSelected(index: number): boolean {
    return this.selectedSectionIndex === index ||
           (this.isCumulative && index < this.selectedSectionIndex);
  }
}

<div class="board">
  <div *ngFor="let section of sections; let i = index"
       [ngClass]="section.css_id"
       [style.border]="isSectionSelected(i) ? '3px solid black' : 'none'"
       (click)="handleSectionClick(i)">
    <img [src]="section.sectionPngPath" style="height: 200px; width: 650px;" alt="Section image">
  </div>

  <button mat-raised-button
          color="primary"
          (click)="handleContinue()"
          [disabled]="selectedSectionIndex < 0"
          style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);">
    Continue
  </button>

  <div style="position: fixed; bottom: 20px; left: 60px;">
    <p>Cumulative?</p>
    <mat-slide-toggle [(ngModel)]="isCumulative" color="primary"></mat-slide-toggle>
  </div>

  <p style="position: fixed; bottom: 55px; right: 6%; font-size: 18px; font-weight: bold;">
    Username: {{playerUsername}}
  </p>

  <button mat-raised-button
          color="warn"
          (click)="handleSignOut()"
          style="position: fixed; bottom: 10px; right: 10px;">
    Sign Out
  </button>

  <button mat-raised-button
          color="primary"
          (click)="openScoreboard()"
          style="position: fixed; bottom: 10px; right: 150px;">
    Scoreboard
  </button>
</div>
