// react-frontend/src/components/Game.tsx
import React, { useState, useEffect } from 'react';
import { sections ,host_api} from '../utils/Constants';
import Timer from './Timer';
import './Game.css'; // Import the CSS file
import { Box, Button, FormControl, InputLabel, MenuItem, Select, SelectChangeEvent, Typography } from '@mui/material';
import { useNavigate } from 'react-router-dom';

interface GameProps {
  selectedSectionsIndex: number;
  playerUsername: string;
  isCumulative: boolean;

}
const Game: React.FC<GameProps> = ({ isCumulative, playerUsername, selectedSectionsIndex }) => {
  const navigate = useNavigate();
  const selectedSections = sections.filter((_, index) => {
    if (isCumulative) {
      return index <= selectedSectionsIndex!
    }
    else {
      return index === selectedSectionsIndex
    }
  });
  const [isAnswerCorrect, setIsAnswerCorrect] = useState<boolean | null>(null); // Track correct answers
  const [isActive, setIsActive] = useState(false);
  const [clickedIndex, setClickedIndex] = useState<number | null>(null);
  const [points, setPoints] = useState<number>(0);
  const [playerLost, setPlayerLost] = useState(false)
  const [timeLeft, setTimeLeft] = useState(100); // 2 minutes
  const [attempts, setAttempts] = useState(0)
  const [numOfLetters, setNumOfLetters] = useState<number>(0); // Strictly type as number
  const [soundClipIndexArr, setSoundClipIndexArr] = useState<number[]>([])
  const [currIndex, setCurrIndex] = useState<number>(0)
  // let  allLetters = selectedSectionsIndex.flatMap(index => sections[index].letters);
  let allLetters = sections[selectedSectionsIndex!].letters
  if (isCumulative) {
    let latest_idx = selectedSectionsIndex! - 1
    while (latest_idx > -1) {
      allLetters = [...allLetters, ...sections[latest_idx].letters]
      latest_idx--
    }
  }

  const handleGoBack = () => {
    navigate('/board')
  }
  const getStyle = (isclicked: boolean) => {
    return {
      display: 'flex',
      justifyContent: 'center',
      cursor: isActive ? 'pointer' : 'default',
      alignItems: 'center',
      // width: '50px',
      // height: '50px',
      // fontSize: '24px',
      backgroundColor: isActive ? 'white' : 'light grey',
      borderRadius: '5px',
      border: isclicked ? '4px solid darkgrey' : '1px solid black',
    }
  }

  const sendData = async (lostSingleLetterGame: boolean) => {
    const data = {
      username: playerUsername,
      points: points,
      letter_level: numOfLetters,
      selected_sections_index:selectedSectionsIndex,
      is_cumulative : isCumulative,
      lost_single_letter_game: lostSingleLetterGame
    };

    try {
      const response = await fetch(`${host_api}/gameover`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });
      const result = await response.json();
    } catch (error) {
      console.error('Error sending data:', error);
    }
  }

  const setGameOver = (endedEarly:boolean) => {
    setIsActive(!isActive)
    setPoints(0)
    // user would not get here if game was single letter and there was one miss 
    if(!endedEarly){
      sendData(false)
    }
  }
  const handleChange = (event: SelectChangeEvent<number>) => {
    setNumOfLetters(Number(event.target.value)); // Ensure the value is converted to number
    switch (Number(event.target.value)) {
      case 1:
        setTimeLeft(7) // 45
        break;
      case 2:
        setTimeLeft(60)
        break;
      case 3:
        setTimeLeft(75)
        break;
      default:
        break;
    }
    setSoundClipIndexArr(Array.from({ length: Number(event.target.value) }, () => Math.floor(Math.random() * allLetters.length)));
  };

  const startgame = () => {
    setPoints(0)
    setIsActive(!isActive)
    setAttempts(prev => prev + 1)
  }

  useEffect(() => {
    if (isActive) {
      setTimeout(() => {
        setIsAnswerCorrect(null)
        const audioArr = soundClipIndexArr.map(index => new Audio(allLetters[index]['audiofilePath']));
        const playAllAudio = async () => {
          for (const audio of audioArr) {
            await playAudio(audio);
          }
        };
        playAllAudio();
      }, 500); // 500 milliseconds = 0.5 seconds

    }
  }, [attempts]);


  const playAudio = (audio: HTMLAudioElement) => {
    return new Promise<void>((resolve) => {
      audio.play();
      audio.onended = () => resolve();
    });
  };


  const handleLetterClick = (letter: string, index: number) => {

    setClickedIndex(index);
    setTimeout(() => setClickedIndex(null), 100); // Border visible for 100ms
    if (letter === allLetters[soundClipIndexArr[currIndex]]['unicode']) {
      setPoints(points => points += 10)
      if (currIndex === soundClipIndexArr.length - 1) {
        setIsAnswerCorrect(true)
        setSoundClipIndexArr(Array.from({ length: Number(numOfLetters) }, () => Math.floor(Math.random() * allLetters.length)));
        setCurrIndex(0)
        setAttempts(prev => prev + 1)
      }
      else {
        setIsAnswerCorrect(true)
        setCurrIndex(currIndex => currIndex += 1)
      }

    }
    else {
      setIsAnswerCorrect(false)
      if(numOfLetters === 1){
        setIsActive(!isActive)
        setPlayerLost(!playerLost)
        sendData(true)
      }
      else{
        
        if (currIndex === soundClipIndexArr.length - 1) {
          setSoundClipIndexArr(Array.from({ length: Number(numOfLetters) }, () => Math.floor(Math.random() * allLetters.length)));
          setCurrIndex(0)
          setAttempts(prev => prev + 1)
        }
        else{
          setCurrIndex(currIndex => currIndex += 1)
        }
       
      }
      
    }
  };

  return (
    <div className="game">
      <div className="center-div">{isActive && (<Timer  timeLeft={timeLeft} setGametimeExpired={setGameOver} />)}</div>
      <div style= {{ position:"fixed", top:"5%", left:"45%", padding:"10px"}}
          >{!isActive && (<>
        <FormControl fullWidth variant="outlined" sx={{ minWidth: 20,marginBottom: 1 }}>
          <InputLabel id="num-of-letters-label">Letters</InputLabel>
          <Select
            labelId="num-of-letters-label"
            id="num-of-letters"
            value={numOfLetters}
            onChange={handleChange}
            label="Num of Letters"
            sx={{ fontSize: '0.875rem', height: '40px' }}  
          >
            <MenuItem value={0}>
              <em>Select a value</em>
            </MenuItem>
            <MenuItem value={1}>1</MenuItem>
            <MenuItem value={2}>2</MenuItem>
            <MenuItem value={3}>3</MenuItem>
          </Select>
        </FormControl>

        <Button variant="contained" 
                color="primary" 
                onClick={startgame} 
                sx={{justifyContent:"center", fontSize: '0.75rem', padding: '6px 6px', minWidth: '80px' }} 
                disabled={numOfLetters === 0}> 
          Start
        </Button>
                     </>)}
      </div>
      <Button 
          variant="contained" 
          color="secondary" 
          onClick={handleGoBack}
          style= {{ position:"fixed", bottom:"20px", left:"50px", marginLeft:"20px" }}
        >
          Back to Board</Button>
    
      <div>{selectedSections.map((section) => (
        <div className={section.css_id} >
          {section.letters.map((letter, index) => {
            // const combinedStyle = { ...divStyles, backgroundColor: section.color };
            const isClicked = index === clickedIndex;
            const thestyle = getStyle(isClicked)
            const combinedStyle = { ...thestyle};
            return (
              <div
                key={index}
                style={combinedStyle}
                onClick={() => isActive ? handleLetterClick(letter['unicode'], index) : null}
              >
                <img src={letter['pngfilePath']} style={{ width: '85px', height: '100px' }}  />
              </div>
            )
          })}
        </div>))}
      </div>
      {isAnswerCorrect && <h3 style={{ color: 'green' }}>Correct</h3>}
      {isAnswerCorrect ===false && <h3 style={{ color: 'red' }}>Incorrect</h3>}
          {isActive && (
      <Typography component="span" 
                  color="primary" 
                  variant="body1"
                  sx= {{ position:"fixed", bottom:"5%", right:"8%" , color: 'black', 
                  fontSize: '24px', 
                  fontWeight: 'bold' }}>
      Points: {points}
    </Typography>)}
    
     
    </div>
  );
};

export default Game;

// angular-frontend/src/app/components/game/game.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { sections, Letter } from '../../utils/constants';
import { ApiService } from '../../core/services/api.service';
import { TimerComponent } from '../timer/timer.component';

@Component({
  selector: 'app-game',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatButtonModule,
    MatFormFieldModule,
    MatSelectModule,
    TimerComponent
  ],
  templateUrl: './game.component.html',
  styleUrl: './game.component.css'
})
export class GameComponent implements OnInit {
  sections = sections;
  selectedSections: any[] = [];
  isCumulative = false;
  selectedSectionsIndex = 0;
  playerUsername = '';

  isAnswerCorrect: boolean | null = null;
  isActive = false;
  clickedIndex: number | null = null;
  points = 0;
  playerLost = false;
  timeLeft = 0;
  attempts = 0;
  numOfLetters = 0;
  soundClipIndexArr: number[] = [];
  currIndex = 0;
  showMessage = false;
  allLetters: Letter[] = [];

  constructor(
    private apiService: ApiService,
    private router: Router
  ) {
    const navigation = this.router.getCurrentNavigation();
    if (navigation?.extras.state) {
      this.selectedSectionsIndex = navigation.extras.state['selectedSectionsIndex'] || 0;
      this.isCumulative = navigation.extras.state['isCumulative'] || false;
      this.playerUsername = navigation.extras.state['playerUsername'] || '';
    }
  }

  ngOnInit(): void {
    this.selectedSections = this.sections.filter((_, index) => {
      if (this.isCumulative) {
        return index <= this.selectedSectionsIndex;
      } else {
        return index === this.selectedSectionsIndex;
      }
    });

    this.allLetters = [...this.sections[this.selectedSectionsIndex].letters];
    if (this.isCumulative) {
      let latestIdx = this.selectedSectionsIndex - 1;
      while (latestIdx > -1) {
        this.allLetters = [...this.allLetters, ...this.sections[latestIdx].letters];
        latestIdx--;
      }
    }
  }

  handleGoBack(): void {
    this.router.navigate(['/board']);
  }

  getStyle(isClicked: boolean): any {
    return {
      display: 'flex',
      justifyContent: 'center',
      cursor: this.isActive ? 'pointer' : 'default',
      alignItems: 'center',
      backgroundColor: this.isActive ? 'white' : 'lightgrey',
      borderRadius: '5px',
      border: isClicked ? '4px solid darkgrey' : '1px solid black'
    };
  }

  sendData(lostSingleLetterGame: boolean): void {
    const data = {
      username: this.playerUsername,
      points: this.points,
      letter_level: this.numOfLetters,
      selected_sections_index: this.selectedSectionsIndex,
      is_cumulative: this.isCumulative,
      lost_single_letter_game: lostSingleLetterGame
    };

    this.apiService.sendGameData(data).subscribe({
      next: (result) => {
        console.log(result);
      },
      error: (error) => {
        console.error('Error sending data:', error);
      }
    });
  }

  setGameOver(endedEarly: boolean): void {
    this.isActive = false;
    this.points = 0;
    if (!endedEarly) {
      this.sendData(false);
    }
  }

  handleChange(value: number): void {
    this.numOfLetters = value;
    switch (value) {
      case 1:
        this.timeLeft = 45;
        break;
      case 2:
        this.timeLeft = 60;
        break;
      case 3:
        this.timeLeft = 75;
        break;
      default:
        break;
    }
    this.soundClipIndexArr = Array.from(
      { length: value },
      () => Math.floor(Math.random() * this.allLetters.length)
    );
  }

  startGame(): void {
    this.points = 0;
    this.isActive = true;
    this.attempts++;

    setTimeout(() => {
      this.isAnswerCorrect = null;
      const audioArr = this.soundClipIndexArr.map(
        index => new Audio(this.allLetters[index].audiofilePath)
      );
      this.playAllAudio(audioArr);
    }, 500);
  }

  async playAllAudio(audioArr: HTMLAudioElement[]): Promise<void> {
    for (const audio of audioArr) {
      await this.playAudio(audio);
      await this.delay(900);
    }
  }

  playAudio(audio: HTMLAudioElement): Promise<void> {
    return new Promise<void>((resolve) => {
      audio.play();
      audio.onended = () => resolve();
    });
  }

  delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  handleLetterClick(letter: string, index: number): void {
    if (!this.isActive) return;

    this.clickedIndex = index;
    setTimeout(() => (this.clickedIndex = null), 100);

    if (letter === this.allLetters[this.soundClipIndexArr[this.currIndex]].unicode) {
      this.points += 10;

      if (this.currIndex === this.soundClipIndexArr.length - 1) {
        this.isAnswerCorrect = true;
        this.showMessageBriefly();
        this.soundClipIndexArr = Array.from(
          { length: this.numOfLetters },
          () => Math.floor(Math.random() * this.allLetters.length)
        );
        this.currIndex = 0;
        this.attempts++;
        setTimeout(() => this.playAllAudio(
          this.soundClipIndexArr.map(idx => new Audio(this.allLetters[idx].audiofilePath))
        ), 500);
      } else {
        this.isAnswerCorrect = true;
        this.showMessageBriefly();
        this.currIndex++;
      }
    } else {
      this.isAnswerCorrect = false;
      this.showMessageBriefly();

      if (this.numOfLetters === 1) {
        this.isActive = false;
        this.playerLost = true;
        this.sendData(true);
      } else {
        if (this.currIndex === this.soundClipIndexArr.length - 1) {
          this.soundClipIndexArr = Array.from(
            { length: this.numOfLetters },
            () => Math.floor(Math.random() * this.allLetters.length)
          );
          this.currIndex = 0;
          this.attempts++;
          setTimeout(() => this.playAllAudio(
            this.soundClipIndexArr.map(idx => new Audio(this.allLetters[idx].audiofilePath))
          ), 500);
        } else {
          this.currIndex++;
        }
      }
    }
  }

  showMessageBriefly(): void {
    this.showMessage = true;
    setTimeout(() => {
      this.showMessage = false;
    }, 500);
  }

  getSectionCssClass(section: any): string {
    if (section.css_id.startsWith('middle-')) {
      return section.css_id === 'middle-left container'
        ? 'middle-left-game container'
        : 'middle-right-game container';
    }
    return section.css_id;
  }
}

<div class="game">
  <div class="center-div" *ngIf="isActive">
    <app-timer [timeLeft]="timeLeft" (gametimeExpired)="setGameOver($event)"></app-timer>
  </div>

  <div style="position: fixed; top: 5%; left: 39%;">
    <div *ngIf="!isActive" style="display: flex; flex-direction: column; align-items: center;">
      <mat-form-field appearance="outline" style="min-width: 20px; margin-bottom: 8px;">
        <mat-label>Letters</mat-label>
        <mat-select [(ngModel)]="numOfLetters" (selectionChange)="handleChange($event.value)">
          <mat-option [value]="0">Select a value</mat-option>
          <mat-option [value]="1">1</mat-option>
          <mat-option [value]="2">2</mat-option>
          <mat-option [value]="3">3</mat-option>
        </mat-select>
      </mat-form-field>

      <button mat-raised-button
              color="primary"
              (click)="startGame()"
              [disabled]="numOfLetters === 0"
              style="min-width: 80px;">
        Start
      </button>
    </div>
  </div>

  <button mat-raised-button
          color="accent"
          (click)="handleGoBack()"
          style="position: fixed; bottom: 20px; left: 70px;">
    Back to Board
  </button>

  <div *ngFor="let section of selectedSections">
    <div [ngClass]="getSectionCssClass(section)">
      <div *ngFor="let letter of section.letters; let i = index"
           [ngStyle]="getStyle(i === clickedIndex)"
           (click)="handleLetterClick(letter.unicode, i)">
        <img [src]="letter.pngfilePath" style="width: 110px; height: 163px;">
      </div>
    </div>
  </div>

  <h3 *ngIf="showMessage"
      [style.color]="isAnswerCorrect ? 'green' : 'red'"
      style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);">
    {{ isAnswerCorrect ? 'Correct' : 'Incorrect' }}
  </h3>

  <p *ngIf="isActive"
     style="position: fixed; bottom: 5%; right: 8%; color: black; font-size: 24px; font-weight: bold;">
    Points: {{ points }}
  </p>
</div>
