// react-frontend/src/components/Timer.tsx

import React, { useEffect, useState } from 'react';
import { formatTime } from '../utils/formatTime';
import { Button } from '@mui/material';

interface TimerProps {
  timeLeft: number;
  setGametimeExpired: (endedEarly:boolean) => void;
}

const Timer: React.FC<TimerProps> = ({ timeLeft, setGametimeExpired }) => {
  const [gameTimeRemaining, setGameTimeRemaining] = useState(timeLeft);

  useEffect(() => {
    const timer = setInterval(() => {
      setGameTimeRemaining((prevTime) => {
        if (prevTime <= 1) {
          clearInterval(timer);
          setGametimeExpired(false);
          return 0;
        }
        return prevTime - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [setGametimeExpired]);

  return (
    <div>
      <h2 style={{textAlign:"center"}}>{formatTime(gameTimeRemaining)}</h2>
      <Button variant="contained" 
                color="primary" onClick={() => setGametimeExpired(true)} >End Game</Button>
    </div>
  );
};

export default Timer;

// angular-frontend/src/app/components/timer/timer.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { formatTime } from '../../utils/format-time';

@Component({
  selector: 'app-timer',
  standalone: true,
  imports: [CommonModule, MatButtonModule],
  templateUrl: './timer.component.html',
  styleUrl: './timer.component.css'
})
export class TimerComponent implements OnInit, OnDestroy {
  @Input() timeLeft: number = 0;
  @Output() gametimeExpired = new EventEmitter<boolean>();

  gameTimeRemaining: number = 0;
  private timer: any;

  ngOnInit(): void {
    this.gameTimeRemaining = this.timeLeft;
    this.timer = setInterval(() => {
      this.gameTimeRemaining--;
      if (this.gameTimeRemaining <= 0) {
        clearInterval(this.timer);
        this.gametimeExpired.emit(false);
      }
    }, 1000);
  }

  ngOnDestroy(): void {
    if (this.timer) {
      clearInterval(this.timer);
    }
  }

  getFormattedTime(): string {
    return formatTime(this.gameTimeRemaining);
  }

  endGame(): void {
    this.gametimeExpired.emit(true);
  }
}

<div>
  <h2 style="text-align: center;">{{ getFormattedTime() }}</h2>
  <button mat-raised-button color="primary" (click)="endGame()">End Game</button>
</div>
