// react-frontend/src/Login.tsx

import React, { useState, ChangeEvent, FormEvent } from 'react';
import { TextField, Button, Container, Typography, Box } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { useAuth } from './AuthContext';

const Login: React.FC = () => {
  const [formValues, setFormValues] = useState({ username: '', password: '' });
  const [error, setError] = useState(false);
  const navigate = useNavigate();
  const { login } = useAuth();

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    const formData = new FormData();
    formData.append('username', formValues.username);
    formData.append('password', formValues.password);
    
    try {
      const response = await fetch('http://127.0.0.1:5000/login', {
        method: 'POST',
        body: formData,
      });

      const result = await response.json();
      if (result.message === "Admin" || result.message === "Regular") {
        login(result.message);
        navigate(result.message === "Admin" ? '/admin' : '/board');
      } else {
        setError(true);
      }
    } catch (error) {
      console.error('Error sending data:', error);
      setError(true);
    }
  };

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormValues({ ...formValues, [name]: value });
  };

  return (
    <Container maxWidth="sm">
       <Box 
        display="flex" 
        flexDirection="column" 
        alignItems="center" 
        justifyContent="center"
        sx={{ mt: 8 }}
      >
        <Typography variant="h3" gutterBottom>
          Welcome to Letter Game
        </Typography>
        <Typography variant="h4" gutterBottom>
          Login
        </Typography>
        <form onSubmit={handleSubmit}>
          <TextField
            label="Username"
            name="username"
            value={formValues.username}
            onChange={handleChange}
            fullWidth
            margin="normal"
            required
          />
          <TextField
            label="Password"
            name="password"
            type="password"
            value={formValues.password}
            onChange={handleChange}
            fullWidth
            margin="normal"
            required
          />
          <Button 
            type="submit" 
            variant="contained" 
            color="primary" 
            fullWidth
            sx={{ mt: 2 }}
          >
            Login
          </Button>
          {error && (
          <Typography variant="body1" color="error" sx={{ mt: 2 }}>
            Authorization failed. Please check your username and password.
          </Typography>
        )}
        </form>
      </Box>
    </Container>
  );
};

export default Login;

// angular-frontend/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { AuthService } from '../../core/services/auth.service';
import { ApiService } from '../../core/services/api.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatCardModule
  ],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  username = '';
  password = '';
  error = false;

  constructor(
    private authService: AuthService,
    private apiService: ApiService,
    private router: Router
  ) {}

  onSubmit(): void {
    const formData = new FormData();
    formData.append('username', this.username);
    formData.append('password', this.password);

    this.apiService.login(formData).subscribe({
      next: (result) => {
        if (result.authenticated) {
          if (result.admin) {
            this.authService.login('Admin', this.username);
            this.router.navigate(['/admin']);
          } else {
            this.authService.login('User', this.username);
            this.router.navigate(['/board']);
          }
        } else {
          this.error = true;
        }
      },
      error: (error) => {
        console.error('Error sending data:', error);
        this.error = true;
      }
    });
  }
}

<div class="login-container">
  <div class="login-box">
    <h1>Letter Game</h1>
    <h2>Login</h2>
    <form (ngSubmit)="onSubmit()">
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Username</mat-label>
        <input matInput [(ngModel)]="username" name="username" required>
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Password</mat-label>
        <input matInput type="password" [(ngModel)]="password" name="password" required>
      </mat-form-field>

      <button mat-raised-button color="primary" type="submit" class="full-width">
        Login
      </button>

      <p *ngIf="error" class="error-message">
        Authorization failed. Please check your username and password.
      </p>
    </form>
  </div>
</div>
